#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=priority-dreamer
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=../output/200M_priority_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/dreamerv3
source activate dreamer

srun python dreamerv3/main.py \
    --logdir $HOME/dreamerv3/logdir/dreamer/{timestamp} \
    --configs atari